// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using hbroconsulting.Models;

namespace hbroconsulting.Migrations
{
    [DbContext(typeof(hbroMoviesContext))]
    [Migration("20220202085605_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("hbroconsulting.Models.movieresponse", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieId");

                    b.ToTable("Responses");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            Category = "Family",
                            Director = "Byron Howard",
                            Edited = false,
                            LentTo = "mom",
                            Notes = "no",
                            Rating = "PG",
                            Title = "Encanto",
                            Year = 2021
                        },
                        new
                        {
                            MovieId = 2,
                            Category = "Comedy",
                            Director = "Akiva Schaffer",
                            Edited = true,
                            LentTo = "Lindy",
                            Notes = "no",
                            Rating = "PG-13",
                            Title = "Hot Rot",
                            Year = 2007
                        },
                        new
                        {
                            MovieId = 3,
                            Category = "Horror/Suspence",
                            Director = "John Krasinski",
                            Edited = false,
                            LentTo = "paul",
                            Notes = "no",
                            Rating = "PG-13",
                            Title = "A Quiet Place",
                            Year = 2018
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
